### PR TITLE
InheritChain-protocol- hack-for-good 

### PR DESCRIPTION
**Pull request by samar19**
InheritChain-protocol
Vision
"Securing Digital Legacies, Today and Tomorrow."
Description
Inheriting Tomorrow, Securing Today: Your Digital Legacy, Powered by InheritChain" In today's digital era, the value of personal assets extends beyond the tangible, encompassing a realm of digital assets including coins, tokens, and NFTs. Surprisingly, a staggering $20 billion worth of these assets has been rendered inaccessible due to the loss of private keys or the unfortunate passing of individuals. In stark contrast to real-world assets like homes, jewelry, and stocks, which are seamlessly transferred to heirs, digital assets often meet an uncertain fate upon the loss of a private key. The question arises: Why not extend the same legacy principles to safeguarding valuable digital assets such as coins and tokens? Introducing the transformative power of the InheritChain Protocol – an innovative solution with the potential to redefine digital legacies. This protocol is the cornerstone of securing digital assets for the future while honoring their importance in the present

### CODE REVIEW

**Comment by owans** [comment]
@samar19 The README has conflicts, please fix and I will merge. Thanks

**Comment by owans** [comment]
@samar19 README still has conflicts. Please resolve. Thanks

**Comment by samar19** [comment]
plz review it and give ur feedback thanks

**Comment by samar19** [comment]
hi Owanate
 thanks for quick reply and ur feedback
plz check it
https://github.com/techrityorg/hack-for-good/pull/5#issuecomment-1765294512

 thanks
samar abdelhameed

**Comment by samar19** [comment]
plz check it 1a7663d1f57ea428927df22a7112b1a1845f1e99

**Pull request merged**
