### PR TITLE
Web3Blockchain: magipop Creathon Submission

### PR DESCRIPTION
**Pull request by DocRace**

### CODE REVIEW

**Comment by owans** [comment]
@DocRace 

I'm unable to merge, please resolve conflicts with the README.

Thanks

**Comment by DocRace** [comment]
Resolved, plz check again

**Comment by owans** [comment]
@DocRace 

Pull the latest changes on the hack-for-good repo
Create a folder with your project name inside the track for which you're applying to
Reorganize the files into your project folder.
Update README of your own project
Push the latest changes to this PR
Thanks

**Comment by DocRace** [comment]
Updated and created a new PR here: https://github.com/techrityorg/hack-for-good/pull/12

**Pull request closed without merging**
